<?php

namespace Database\Seeders;

use App\Models\Charge;
use Illuminate\Database\Seeder;

class ChargeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $charges = [
            ['charge_name' => 'كشف استشارى', 'standard_charge' => 400],
            ['charge_name' => 'كشف', 'standard_charge' => 300],
            ['charge_name' => 'مراجعة', 'standard_charge' => 0],
            ['charge_name' => 'COMPLETE BLOOD COUNT (CBC)', 'standard_charge' => 64],
            ['charge_name' => 'ERYTHROCYTES SEDIMENTATION', 'standard_charge' => 80],
            ['charge_name' => 'ANTINUCLEAR ANTIBODIES (ANA)', 'standard_charge' => 192],
            ['charge_name' => 'HAIR CARE LAB. PACKAGE', 'standard_charge' => 550],
            ['charge_name' => 'ROAKUTAN PACKAGE #2', 'standard_charge' => 450],
            ['charge_name' => 'ANTI THYROID PEROXIDASE ABS(TPO)', 'standard_charge' => 400],
            ['charge_name' => 'HEPATITIS B VIRUS SURFACE', 'standard_charge' => 180],
            ['charge_name' => 'HEPATITIS B SURFACE (HBs)', 'standard_charge' => 360],
            ['charge_name' => 'HEPATITIS C VIRUS (HCV) A', 'standard_charge' => 180],
            ['charge_name' => 'ANTI THYROGLOBULIN (A-TG)', 'standard_charge' => 180],
            ['charge_name' => 'roaccutan package #1', 'standard_charge' => 500],
            ['charge_name' => 'Ferritin in serum', 'standard_charge' => 96],
            ['charge_name' => 'Thyroid Stimulating Hormone(TSH)', 'standard_charge' => 160],
            ['charge_name' => 'Vitamin D(25 OH -Vit d- total )', 'standard_charge' => 100],
            ['charge_name' => 'Transferrin,Serum', 'standard_charge' => 250],
            ['charge_name' => 'Triiodothyronin -Free (FT3),Serum', 'standard_charge' => 100],
            ['charge_name' => 'Triiodothyronin -Free (FT4),Serum', 'standard_charge' => 100],
            ['charge_name' => 'Botox face 1ml', 'standard_charge' => 2000],
            ['charge_name' => 'Botox face and neck', 'standard_charge' => 3000],
            ['charge_name' => 'Botox gummy smile', 'standard_charge' => 800],
            ['charge_name' => 'Botox crows feet', 'standard_charge' => 800],
            ['charge_name' => 'Botox nose', 'standard_charge' => 800],
            ['charge_name' => 'Botox underarms', 'standard_charge' => 3000],
            ['charge_name' => 'Botox hyperhidrosis hand', 'standard_charge' => 3000],
            ['charge_name' => 'Botox hyperhidrosis feet', 'standard_charge' => 4000],
            ['charge_name' => 'Botox neck', 'standard_charge' => 2000],
            ['charge_name' => 'Mesobotox', 'standard_charge' => 1500],
            ['charge_name' => 'Teosyeal filler 1 ml', 'standard_charge' => 2000],
            ['charge_name' => 'Aliaxin filler 1ml', 'standard_charge' => 2000],
            ['charge_name' => 'Skinfill filler 1ml', 'standard_charge' => 1600],
            ['charge_name' => 'Restylane filler 1 ml', 'standard_charge' => 2000],
            ['charge_name' => 'Skinfill body filler 10 ml', 'standard_charge' => 3000],
            ['charge_name' => 'Skinfill body filler 50 ml', 'standard_charge' => 15000],
            ['charge_name' => 'PDO thread', 'standard_charge' => 800],
            ['charge_name' => 'PLX thread', 'standard_charge' => 1000],
            ['charge_name' => 'Aptos thread', 'standard_charge' => 2000],
            ['charge_name' => 'Silhouette thread', 'standard_charge' => 2500],
            ['charge_name' => 'Mono thread', 'standard_charge' => 500],
            ['charge_name' => 'Mesotherapy', 'standard_charge' => 1000],
            ['charge_name' => 'Stem cell for skin', 'standard_charge' => 1500],
            ['charge_name' => 'Stem cell for hair', 'standard_charge' => 1500],
            ['charge_name' => 'ASce exosomes for skin', 'standard_charge' => 1500],
            ['charge_name' => 'ASce exosomes for hair', 'standard_charge' => 1500],
            ['charge_name' => 'Profhilo 2 ml', 'standard_charge' => 2000],
            ['charge_name' => 'Neuckloskin 3 ml', 'standard_charge' => 3000],
            ['charge_name' => 'Neucklofill', 'standard_charge' => 3000],
            ['charge_name' => 'Skinfill blue', 'standard_charge' => 3000],
            ['charge_name' => 'Persebelle 3 ml', 'standard_charge' => 2500],
            ['charge_name' => 'Persebelle 5 ml', 'standard_charge' => 4000],
            ['charge_name' => 'Dorthy', 'standard_charge' => 2500],
            ['charge_name' => 'Neofound', 'standard_charge' => 2000],
            ['charge_name' => 'Hydro deluxe', 'standard_charge' => 2000],
            ['charge_name' => 'Innovyal 1 ml', 'standard_charge' => 1300],
            ['charge_name' => 'Innovyal 3ml', 'standard_charge' => 3000],
            ['charge_name' => 'Normal Plasma Promoitalia', 'standard_charge' => 1500],
            ['charge_name' => 'Plasma HA Promoitalia (supervision of Dr. Hani)', 'standard_charge' => 2000],
            ['charge_name' => 'Plasma biotin Promoitalia (supervision of Dr. Hani)', 'standard_charge' => 1800],
            ['charge_name' => 'Regan lab plasma', 'standard_charge' => 2000],
            ['charge_name' => 'Sculptra 10 ml', 'standard_charge' => 5000],
            ['charge_name' => 'Rich 10 ml', 'standard_charge' => 6000],
            ['charge_name' => 'Lanluma', 'standard_charge' => 4000],
            ['charge_name' => 'Radiesse filler', 'standard_charge' => 3000],
            ['charge_name' => 'Fat lypolysis injection double chain', 'standard_charge' => 1500],
            ['charge_name' => 'Fat lypolysis injection body', 'standard_charge' => 3000],
            ['charge_name' => 'Tca peeling small area', 'standard_charge' => 1000],
            ['charge_name' => 'Tca peeling medium area', 'standard_charge' => 2000],
            ['charge_name' => 'Tca large area', 'standard_charge' => 3000],
            ['charge_name' => 'Full body hair removal laser', 'standard_charge' => 2000],
            ['charge_name' => 'Mini body hair removal laser', 'standard_charge' => 1500],
            ['charge_name' => 'Face hair removal laser', 'standard_charge' => 600],
            ['charge_name' => 'Eyebrow hair removal laser', 'standard_charge' => 600],
            ['charge_name' => 'Mustache hair removal laser', 'standard_charge' => 500],
            ['charge_name' => 'Underarms hair removal laser (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Bikini hair removal laser', 'standard_charge' => 1000],
            ['charge_name' => 'Legs hair removal laser', 'standard_charge' => 1000],
            ['charge_name' => 'Back hair removal laser', 'standard_charge' => 1500],
            ['charge_name' => 'Arms hair removal laser', 'standard_charge' => 1500],
            ['charge_name' => 'Chest hair removal laser', 'standard_charge' => 1000],
            ['charge_name' => 'Abdomen hair removal laser', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for face (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Neck (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Chest (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for Abdomen (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for Back (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for Arms (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for Leg (supervision of Dr. Hani)', 'standard_charge' => 2000],
            ['charge_name' => 'Picoway laser for Buttocks (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Picoway laser for Bikini (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Underarms (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Hand (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Knee (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Elbow (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for Feets (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser Full body (supervision of Dr. Hani)', 'standard_charge' => 7000],
            ['charge_name' => 'Eyebrow Tattoo removal by Picoway', 'standard_charge' => 700],
            ['charge_name' => 'Tattoo removal small area by Picoway', 'standard_charge' => 1000],
            ['charge_name' => 'Tattoo removal medium area by Picoway', 'standard_charge' => 1500],
            ['charge_name' => 'Tattoo removal large area by Picoway', 'standard_charge' => 2000],
            ['charge_name' => 'Hydra touch deep cleaning', 'standard_charge' => 1000],
            ['charge_name' => 'Hydratouch deep cleaning with vitamins', 'standard_charge' => 1500],
            ['charge_name' => 'Dermapen with mesotherapy', 'standard_charge' => 1000],
            ['charge_name' => 'Dermapen with stem cell', 'standard_charge' => 1500],
            ['charge_name' => 'Dermapen with exosomes', 'standard_charge' => 1500],
            ['charge_name' => 'Face mask', 'standard_charge' => 250],
            ['charge_name' => 'Ultraformer MPT face (supervision of Dr. Hani)', 'standard_charge' => 3000],
            ['charge_name' => 'Ultraformer MPT neck (supervision of Dr. Hani)', 'standard_charge' => 2000],
            ['charge_name' => 'Ultraformer MPT face and neck (supervision of Dr. Hani)', 'standard_charge' => 4500],
            ['charge_name' => 'Ultraformer MPT double chain (supervision of Dr. Hani)', 'standard_charge' => 2000],
            ['charge_name' => 'Ultraformer MPT jawline (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Ultraformer MPT eyebrow (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Genius treatment for face', 'standard_charge' => 2500],
            ['charge_name' => 'Genius treatment for body', 'standard_charge' => 3500],
            ['charge_name' => 'Frax laser face', 'standard_charge' => 1500],
            ['charge_name' => 'Frax laser face and neck', 'standard_charge' => 2000],
            ['charge_name' => 'Frax laser body', 'standard_charge' => 3000],
            ['charge_name' => 'Frax laser small area', 'standard_charge' => 1500],
            ['charge_name' => 'Frax laser large area', 'standard_charge' => 3000],
            ['charge_name' => 'Frax laser small scar', 'standard_charge' => 800],
            ['charge_name' => 'Frax laser for face + normal plasma + stem cell + subsession offer', 'standard_charge' => 1800],
            ['charge_name' => 'Frax laser for face + stem cell + mask offer', 'standard_charge' => 1800],
            ['charge_name' => 'Frax laser for face + exosomes + mask offer', 'standard_charge' => 2000],
            ['charge_name' => 'Genius treatment for face + stem cell + mask offer', 'standard_charge' => 1600],
            ['charge_name' => 'Genius treatment for face + exosomes + mask + Subsession + stem cell offer', 'standard_charge' => 2800],
            ['charge_name' => 'Picoway laser for face + topical stem cell for whitening offer (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Picoway laser for face and neck + topical stem cell whitening offer (supervision of Dr. Hani)', 'standard_charge' => 1300],
            ['charge_name' => 'Picoway laser for underarms + topical stem cell whitening offer (supervision of Dr. Hani)', 'standard_charge' => 1300],
            ['charge_name' => 'Picoway laser for bikini + topical stem cell whitening offer (supervision of Dr. Hani)', 'standard_charge' => 1300],
            ['charge_name' => 'Picoway laser for face offer (supervision of Dr. Hani)', 'standard_charge' => 650],
            ['charge_name' => 'Picoway laser for face and neck offer (supervision of Dr. Hani)', 'standard_charge' => 850],
            ['charge_name' => 'Picoway laser for knee offer (supervision of Dr. Hani)', 'standard_charge' => 700],
            ['charge_name' => 'Picoway laser for elbow offer (supervision of Dr. Hani)', 'standard_charge' => 750],
            ['charge_name' => 'Picoway laser for underarms offer (supervision of Dr. Hani)', 'standard_charge' => 750],
            ['charge_name' => 'Picoway laser for bikini offer (supervision of Dr. Hani)', 'standard_charge' => 750],
            ['charge_name' => 'Picoway laser for hands offer (supervision of Dr. Hani)', 'standard_charge' => 750],
            ['charge_name' => 'Picoway laser for feet offer (supervision of Dr. Hani)', 'standard_charge' => 750],
            ['charge_name' => 'Picoway laser for lips offer (supervision of Dr. Hani)', 'standard_charge' => 450],
            ['charge_name' => 'Picoway laser for eyebrow tattoo removal offer (supervision of Dr. Hani)', 'standard_charge' => 450],
            ['charge_name' => 'Botox 1 ml offer', 'standard_charge' => 1000],
            ['charge_name' => 'Skinfill filler 1 ml offer', 'standard_charge' => 1150],
            ['charge_name' => 'Teosyeal 1 ml offer', 'standard_charge' => 1300],
            ['charge_name' => 'Opera filler 1ml offer', 'standard_charge' => 1150],
            ['charge_name' => 'Aliaxin filler 1ml offer', 'standard_charge' => 1200],
            ['charge_name' => 'Restylane filler 1 ml offer', 'standard_charge' => 1300],
            ['charge_name' => 'Normal plasma promoitalia offer', 'standard_charge' => 800],
            ['charge_name' => 'Plasma HA Promoitalia offer (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Plasma biotin Promoitalia offer (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'Plasma biotin Promoitalia + stem cell for hair offer (supervision of Dr. Hani)', 'standard_charge' => 1600],
            ['charge_name' => 'Botox crows feet offer', 'standard_charge' => 500],
            ['charge_name' => 'Botox neck offer', 'standard_charge' => 600],
            ['charge_name' => 'Botox face and neck offer', 'standard_charge' => 1800],
            ['charge_name' => 'Botox gummy smile offer', 'standard_charge' => 500],
            ['charge_name' => 'Botox hyperhidrosis hand offer', 'standard_charge' => 1600],
            ['charge_name' => 'Botox underarms hyperhidrosis offer', 'standard_charge' => 1600],
            ['charge_name' => 'Ultraformer MPT face offer (supervision of Dr. Hani)', 'standard_charge' => 2000],
            ['charge_name' => 'Ultraformer MPT face and neck offer (supervision of Dr. Hani)', 'standard_charge' => 2500],
            ['charge_name' => 'Ultraformer MPT neck offer (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Ultraformer MPT double chain offer (supervision of Dr. Hani)', 'standard_charge' => 1500],
            ['charge_name' => 'Persebelle 3 ml offer', 'standard_charge' => 1200],
            ['charge_name' => 'Dorthy offer', 'standard_charge' => 1500],
            ['charge_name' => 'Profhilo 2 ml offer', 'standard_charge' => 1500],
            ['charge_name' => 'Neuckloskin 3 ml offer', 'standard_charge' => 1800],
            ['charge_name' => 'Neucklofill offer', 'standard_charge' => 1800],
            ['charge_name' => 'Skinfill blue offer', 'standard_charge' => 1800],
            ['charge_name' => 'Sculptra 10 ml offer', 'standard_charge' => 3500],
            ['charge_name' => 'Rich 10 ml offer', 'standard_charge' => 4500],
            ['charge_name' => 'Stem cell for hair offer', 'standard_charge' => 800],
            ['charge_name' => 'Stem cell for skin offer', 'standard_charge' => 800],
            ['charge_name' => 'ASce exosomes for skin offer', 'standard_charge' => 1500],
            ['charge_name' => 'ASce exosomes for hair offer', 'standard_charge' => 1500],
            ['charge_name' => 'Innovyal 1 ml offer', 'standard_charge' => 800],
            ['charge_name' => 'Innovyal 3ml offer', 'standard_charge' => 2000],
            ['charge_name' => 'Hdracool deep cleaning with vitamin for face offer', 'standard_charge' => 500],
            ['charge_name' => 'Hydratouch session for deep facial cleansing', 'standard_charge' => 399],
            ['charge_name' => 'PDO thread offer', 'standard_charge' => 400],
            ['charge_name' => 'Mesotherapy offer', 'standard_charge' => 800],
            ['charge_name' => 'Jalupro', 'standard_charge' => 3000],
            ['charge_name' => 'Exosome for skin', 'standard_charge' => 2000],
            ['charge_name' => 'Exosome for hair', 'standard_charge' => 2000],
            ['charge_name' => 'Exosome for skin offer', 'standard_charge' => 1500],
            ['charge_name' => 'Exosome for hair offer', 'standard_charge' => 1500],
            ['charge_name' => 'Accure Face', 'standard_charge' => 5000],
            ['charge_name' => 'Accure Face offer', 'standard_charge' => 4500],
            ['charge_name' => 'Accure Body', 'standard_charge' => 6000],
            ['charge_name' => 'Accure Body offer', 'standard_charge' => 5000],
            ['charge_name' => 'Dissolve Filler Hyaluronidase', 'standard_charge' => 850],
            ['charge_name' => 'Rich 5 ml', 'standard_charge' => 2000],
            ['charge_name' => 'Persebelle 1ml', 'standard_charge' => 850],
            ['charge_name' => 'Persebelle 5 ml offer', 'standard_charge' => 1500],
            ['charge_name' => 'Persebelle lighting 5 ml', 'standard_charge' => 1000],
            ['charge_name' => '3ML FILLER + 1ML BOTOX + MESOTHERAPY', 'standard_charge' => 4500],
            ['charge_name' => 'COLD PEELING + HOME CARE', 'standard_charge' => 2500],
            ['charge_name' => 'BOTOX 2ML OFFER', 'standard_charge' => 1800],
            ['charge_name' => 'JALUPRO OFFER', 'standard_charge' => 1800],
            ['charge_name' => 'TCA SMALL AREA OFFER', 'standard_charge' => 700],
            ['charge_name' => 'TCA LARGE AREA OFFER', 'standard_charge' => 1000],
            ['charge_name' => 'A CELL MATRIX', 'standard_charge' => 5000],
            ['charge_name' => 'A CELL MATRIX + PLASMA BIOTIN OFFER', 'standard_charge' => 4000],
            ['charge_name' => 'COLD PEELING', 'standard_charge' => 1500],
            ['charge_name' => 'COLD PEELING OFFER', 'standard_charge' => 950],
            ['charge_name' => 'COLD PEELING + HOME CARE OFFER', 'standard_charge' => 1800],
            ['charge_name' => 'LIGHTING INJECTION AND PIGMENTATION TREATMENT', 'standard_charge' => 2500],
            ['charge_name' => 'LIGHTING INJECTION AND PIGMENTATION TREATMENT OFFER', 'standard_charge' => 1000],
            ['charge_name' => 'WARTS REMOVAL WITH CRYO - ADULT', 'standard_charge' => 250],
            ['charge_name' => 'WARTS REMOVAL WITH CRYO - CHILDREN', 'standard_charge' => 150],
            ['charge_name' => 'HYDRAFACIAL WITH DERMAPEN', 'standard_charge' => 650],
            ['charge_name' => 'INTRALESIONAL STEROID SINGLE LESION', 'standard_charge' => 300],
            ['charge_name' => 'INTRALESIONAL STEROID MULTIPLE LESIONS', 'standard_charge' => 600],
            ['charge_name' => 'INTRALESIONAL STEROID FOR WHOLE SCALP', 'standard_charge' => 1000],
            ['charge_name' => 'COSMOLAN TRANX HOME CARE', 'standard_charge' => 1000],
            ['charge_name' => 'ALLRFIN AMP', 'standard_charge' => 30],
            ['charge_name' => 'DAXAMESTHASON AMP', 'standard_charge' => 80],
            ['charge_name' => 'Skin booster injection', 'standard_charge' => 3000],
            ['charge_name' => 'Skin booster injection offer', 'standard_charge' => 1500],
            ['charge_name' => 'STYLAGE FILLER 1ML', 'standard_charge' => 1500],
            ['charge_name' => 'ELECTROCAUTERY FOR SINGLE LESION', 'standard_charge' => 250],
            ['charge_name' => 'ELECTROCAUTERY FOR 2 LESIONS', 'standard_charge' => 400],
            ['charge_name' => 'ELECTROCAUTERY FOR 3 LESIONS', 'standard_charge' => 500],
            ['charge_name' => 'SUBCISION + EXOSOME', 'standard_charge' => 1550],
            ['charge_name' => 'MCCN-PDRN-1ML', 'standard_charge' => 400],
            ['charge_name' => 'KENALOUG INJECTION', 'standard_charge' => 400],
            ['charge_name' => 'Genius treatment for face + exosomes + mask offer', 'standard_charge' => 3000],
            ['charge_name' => 'DERMAPEN', 'standard_charge' => 450],
            ['charge_name' => 'ULTRAFORMER + SALMONDNA (supervision of Dr. Hani)', 'standard_charge' => 3000],
            ['charge_name' => 'PDRN INJECTION', 'standard_charge' => 1500],
            ['charge_name' => 'FRAX PRO + EXOSOME + SUBCISION + MASK COCKTAIL STEM CELLS OFFER', 'standard_charge' => 2000],
            ['charge_name' => 'BOTOX AROUND EYE OFFER', 'standard_charge' => 600],
            ['charge_name' => 'BOTOX FULL FACE OFFER', 'standard_charge' => 1600],
            ['charge_name' => 'BOTOX FOREHEAD & AROUND EYE OFFER', 'standard_charge' => 1300],
            ['charge_name' => 'BOTOX NOSE OFFER', 'standard_charge' => 600],
            ['charge_name' => 'JAWLINE BOTOX (Nefertiti) OFFER', 'standard_charge' => 600],
            ['charge_name' => 'BOTOX FOREHEAD & AROUND EYE', 'standard_charge' => 1300],
            ['charge_name' => 'Tattoo Removal Small Area By Picoway offer (supervision of Dr. Hani)', 'standard_charge' => 500],
            ['charge_name' => 'Tattoo Removal Large Area By Picoway offer (supervision of Dr. Hani)', 'standard_charge' => 1000],
            ['charge_name' => 'ACCURE TIP', 'standard_charge' => 500],
            ['charge_name' => 'Penthrox inhalation', 'standard_charge' => 400],
            ['charge_name' => '1ml exosomes topical', 'standard_charge' => 400],
            ['charge_name' => 'Sefera Injection offer', 'standard_charge' => 3000],
            ['charge_name' => 'Sefera Injection', 'standard_charge' => 4000],
            ['charge_name' => 'Extra Mask for hydrofascial', 'standard_charge' => 200],
            ['charge_name' => 'Deep cleansing for Sensitive skin', 'standard_charge' => 350],
            ['charge_name' => 'Deep cleansing for oil skin', 'standard_charge' => 350],
            ['charge_name' => 'Deep cleansing for acne - prone skin', 'standard_charge' => 499],
            ['charge_name' => 'Mini facial session with a mask', 'standard_charge' => 250],
            ['charge_name' => 'Deep facial cleansing with scrub and mask for hand, eyes, lips and face', 'standard_charge' => 550],
            ['charge_name' => 'Mini facial session with eye care', 'standard_charge' => 350],
            ['charge_name' => 'Deep cleansing session with peeling and skin tone unification', 'standard_charge' => 350],
            ['charge_name' => 'Eye Care session', 'standard_charge' => 199],
            ['charge_name' => 'Hadra session with deep facial cleansing and vitamin C Mask', 'standard_charge' => 699],
            ['charge_name' => '4 Deep facial cleansing sessions with an additional session (eye) or (hand, lips, neck, collagen and eye)', 'standard_charge' => 1499],
            ['charge_name' => 'Haydra session for underarm area with whitening and brightening', 'standard_charge' => 399],
            ['charge_name' => 'Haydra session for full back area with mask', 'standard_charge' => 1299],
            ['charge_name' => 'Tca Peeling small area offer', 'standard_charge' => 700],
            ['charge_name' => 'Botox Full Face offer', 'standard_charge' => 1600],
            ['charge_name' => 'Genius treatment for face + exosomes + mask + stem cell offer', 'standard_charge' => 3000],
        ];

        foreach ($charges as $charge) {
            Charge::updateOrCreate([
                'charge_name' => $charge['charge_name'],
            ],[
                'charge_type_id' => 2,
                'charge_category_id' => 1,
                'unit_type_id' => 4,
                'tax_id' => 1,
                'tax_percentage' => 0,
                'charge_name' => $charge['charge_name'],
                'standard_charge' => $charge['standard_charge'],
                'description' => null,
            ]);
        }
    }
}
