version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: clinic_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    ports:
      - "9001:9000"
    networks:
      - clinic

  nginx:
    image: nginx:latest
    container_name: clinic_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - clinic

  mysql:
    image: mysql:8
    container_name: clinic_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - clinic

  composer:
    image: composer:latest
    container_name: clinic_composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: install

  npm:
    image: node:20
    container_name: clinic_npm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: clinic_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: clinic_user
      PMA_PASSWORD: clinic_pass
    networks:
      - clinic

volumes:
  db_data:

networks:
  clinic:
    driver: bridge
